name: Node Pipeline

on:
  push:
    branches: ["main"]

jobs:
  node:
    runs-on: ["wsl-ubuntu-pvk"]

    steps:
      - name: Clone the code
        uses: actions/checkout@v7

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: 24

      - name: Install Dependencies
        run: npm install

      - name: Run Node Application
        run: |
          node app.js &
          sleep 5
          curl http://localhost:8080
          curl http://localhost:8080/health
          pkill -f "node app.js"
          
